# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aiproxy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aiproxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raiproxy.proto\x12\x07\x61iproxy\"\xaa\x01\n\x11\x43ompletionRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x0e\n\x06system\x18\x04 \x01(\t\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05\x12\x0f\n\x07project\x18\x06 \x01(\t\x12\r\n\x05group\x18\x07 \x01(\t\x12\x0c\n\x04tier\x18\x08 \x01(\t\x12\x12\n\nusage_type\x18\t \x01(\t\"\x95\x01\n\x12\x43ompletionResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x14\n\x0cinput_tokens\x18\x02 \x01(\x05\x12\x15\n\routput_tokens\x18\x03 \x01(\x05\x12\x12\n\nlatency_ms\x18\x04 \x01(\x05\x12\x14\n\x0c\x61\x63tual_model\x18\x05 \x01(\t\x12\x17\n\x0f\x61\x63tual_provider\x18\x06 \x01(\t\"0\n\x0f\x43ompletionChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x32\x98\x01\n\x07\x41IProxy\x12\x43\n\x08\x43omplete\x12\x1a.aiproxy.CompletionRequest\x1a\x1b.aiproxy.CompletionResponse\x12H\n\x0eStreamComplete\x12\x1a.aiproxy.CompletionRequest\x1a\x18.aiproxy.CompletionChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiproxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLETIONREQUEST']._serialized_start=27
  _globals['_COMPLETIONREQUEST']._serialized_end=197
  _globals['_COMPLETIONRESPONSE']._serialized_start=200
  _globals['_COMPLETIONRESPONSE']._serialized_end=349
  _globals['_COMPLETIONCHUNK']._serialized_start=351
  _globals['_COMPLETIONCHUNK']._serialized_end=399
  _globals['_AIPROXY']._serialized_start=402
  _globals['_AIPROXY']._serialized_end=554
# @@protoc_insertion_point(module_scope)
