# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aiproxy_pb2 as aiproxy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aiproxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/aiproxy.AIProxy/Complete',
                request_serializer=aiproxy__pb2.CompletionRequest.SerializeToString,
                response_deserializer=aiproxy__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.StreamComplete = channel.unary_stream(
                '/aiproxy.AIProxy/StreamComplete',
                request_serializer=aiproxy__pb2.CompletionRequest.SerializeToString,
                response_deserializer=aiproxy__pb2.CompletionChunk.FromString,
                _registered_method=True)


class AIProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=aiproxy__pb2.CompletionRequest.FromString,
                    response_serializer=aiproxy__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamComplete': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamComplete,
                    request_deserializer=aiproxy__pb2.CompletionRequest.FromString,
                    response_serializer=aiproxy__pb2.CompletionChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiproxy.AIProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiproxy.AIProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiproxy.AIProxy/Complete',
            aiproxy__pb2.CompletionRequest.SerializeToString,
            aiproxy__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiproxy.AIProxy/StreamComplete',
            aiproxy__pb2.CompletionRequest.SerializeToString,
            aiproxy__pb2.CompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
